# Uninstrumented deployment for kubernetes
# Before deploying it, run "make build-all push-all"
# as it requires to manually load the images to the local K8s cluster (e.g. kind load-image)
apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: frontend
  namespace: demo
spec:
  selector:
    matchLabels:
      app: frontend
#  replicas: 1
  template:
    metadata:
      annotations:
        resource.opentelemetry.io/service.name: "my-frontend"
        resource.opentelemetry.io/service.namespace: "ecommerce"
        resource.opentelemetry.io/deployment.environment: "staging"
      labels:
        app: frontend
        grafana.com/instrument-port: "8080"
    spec:
      containers:
        - name: frontend
          image: mariomac/ds-frontend
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: BACKEND
              value: http://backend:8080

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: demo
spec:
  selector:
    app: frontend
  ports:
    - port: 8080
      protocol: TCP
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: demo
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
        grafana.com/instrument-port: "8080"
      annotations:
        resource.opentelemetry.io/service.name: "my-backend"
        resource.opentelemetry.io/service.namespace: "ecommerce"
        resource.opentelemetry.io/deployment.environment: "staging"
    spec:
      containers:
        - name: frontend
          image: mariomac/ds-backend
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: WORKERS
              value: "worker:5000"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: demo
spec:
  selector:
    app: backend
  ports:
    - port: 8080
      protocol: TCP
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: demo
spec:
  selector:
    matchLabels:
      app: worker
  replicas: 3
  template:
    metadata:
      labels:
        app: worker
        grafana.com/instrument-port: "5000"
    spec:
      containers:
        - name: frontend
          image: mariomac/ds-worker
          ports:
            - containerPort: 5000
              name: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: worker
  namespace: demo
spec:
  selector:
    app: worker
  ports:
    - port: 5000
      targetPort: grpc
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-loadgen
  namespace: demo
spec:
  containers:
    - name: loadgen
      image: mariomac/ds-loadgen
      env:
        - name: "WAIT_TIME"
          value: "1s"
        - name: "FRONTEND"
          value: "http://frontend:8080"
