# deploy with:
# helm repo add grafana https://grafana.github.io/helm-charts
# helm install alloy grafana/alloy -f ./alloy-values.yml
alloy:
  envFrom:
    - configMapRef:
        name: grafana-creds
  configMap:
    content: |-
      logging {
        level  = "debug"
      }
      prometheus.scrape "LABEL" {
        targets    = [
          {"__address__" = "beyla:9090"},
        ]
        forward_to = [prometheus.remote_write.grafanacloud.receiver]
        scrape_interval = "10s"
        metrics_path    = "/metrics"
        honor_labels    = true
      }
      
      prometheus.remote_write "grafanacloud" {
        endpoint {
          url = env("MIMIR_ENDPOINT")
          
          basic_auth {
            username = env("MIMIR_USER")
            password = env("GRAFANA_API_KEY")
          }
        }
      }
