apiVersion: v1
kind: ConfigMap
metadata:
  name: beyla-config
data:
  beyla-config.yml: |
    grafana:
      otlp:
        submit: ["metrics","traces"]
    otel_traces_export:
      sampler:
        name: parentbased_traceidratio
        arg: "0.01"
    routes:
      patterns:
        - /factorial/{num}
    discovery:
      services:
        - exe_path_regexp: (worker)|(backend)|(frontend)
          namespace: huge_factorial_calculator
        - exe_path_regexp: loadgen
          namespace: testing
          name: "TestLoadGenerator"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: beyla
spec:
  selector:
    matchLabels:
      instrumentation: beyla
  template:
    metadata:
      labels:
        instrumentation: beyla
    spec:
      hostPID: true  #important!
      volumes:
        - name: beyla-config
          configMap:
            name: beyla-config
      containers:
        - name: beyla
          image: grafana/beyla:1.0
          imagePullPolicy: IfNotPresent
          command: ["/beyla", "--config=/config/beyla-config.yml"]
          securityContext:
            privileged: true
            runAsUser: 0
          volumeMounts:
            - mountPath: /config
              name: beyla-config
          env:
            - name: GRAFANA_OTLP_CLOUD_ZONE
              value: prod-eu-west-0
            - name: GRAFANA_OTLP_CLOUD_INSTANCE_ID
              valueFrom:
                secretKeyRef:
                  key: grafana-user
                  name: grafana-secret
            - name: GRAFANA_OTLP_CLOUD_API_KEY
              valueFrom:
                secretKeyRef:
                  key: grafana-api-key
                  name: grafana-secret
