apiVersion: v1
kind: ConfigMap
metadata:
  name: beyla-config
data:
  beyla-config.yml: |
    print_traces: true
    log_level: debug
    discovery:
      services:
        # just instrument any process opening a port
        # Beyla will decide automatically the service name
        - exe_path_regexp: .
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: beyla
spec:
  selector:
    matchLabels:
      instrumentation: beyla
  template:
    metadata:
      labels:
        instrumentation: beyla
    spec:
      hostPID: true  #important!
      volumes:
        - name: beyla-config
          configMap:
            name: beyla-config
      containers:
        - name: beyla
          image: grafana/beyla:0.3.3
          command: ["/beyla", "--config=/config/beyla-config.yml"]
          securityContext:
            privileged: true
            runAsUser: 0
          volumeMounts:
            - mountPath: /config
              name: beyla-config
          env:
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "http/protobuf"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://grafana-agent:4318"

