apiVersion: v1
kind: ServiceAccount
metadata:
  name: beyla
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: beyla
rules:
  - apiGroups: [ "apps" ]
    resources: [ "replicasets" ]
    verbs: [ "list", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "pods", "services", "nodes" ]
    verbs: [ "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: beyla
subjects:
  - kind: ServiceAccount
    name: beyla
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: beyla
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: beyla-config
data:
  beyla-config.yml: |
    #    filter:
    #      application:
    #        client:
    #          not_match: 'backend'
    #        server:
    #          not_match: 'backend'
    # log_level: debug
    # trace_printer: text
    # routes:
    #   unmatched: heuristic
    # discovery:
      # allow_self_instrumentation: true
      # services:
      #   - k8s_daemonset_name: beyla
      #   - k8s_namespace: demo
    attributes:
      kubernetes:
        enable: true
      select:
        "*":
          include: [ "*" ]
          exclude: ["url_path"]
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: beyla
spec:
  selector:
    matchLabels:
      instrumentation: beyla
  template:
    metadata:
      labels:
        instrumentation: beyla
    spec:
      serviceAccountName: beyla
      hostPID: true  #important for app instrumentation
      hostNetwork: true #important for network metrics
      volumes:
        - name: beyla-config
          configMap:
            name: beyla-config
      containers:
        - name: beyla
#          image: grafana/beyla:1.9
          image: grafana/beyla:main
          #image: docker.io/mariomac/beyla:dev
          imagePullPolicy: Always
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /config
              name: beyla-config
          ports:
            - containerPort: 9090
              name: http
            - containerPort: 6060
              name: pprof
          env:
            # - name: BEYLA_LOG_LEVEL
            #   value: "debug"
            #            - name: BEYLA_BPF_DEBUG
            #              value: "true"
#            - name: BEYLA_PRINT_TRACES
#              value: "true"
            - name: BEYLA_PROFILE_PORT
              value: "6060"
            - name: BEYLA_CONFIG_PATH
              value: "/config/beyla-config.yml"
            - name: BEYLA_KUBE_METADATA_ENABLE
              value: "true"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "https://otlp-gateway-prod-eu-west-0.grafana.net/otlp"
            - name: OTEL_EXPORTER_OTLP_HEADERS
              valueFrom:
                secretKeyRef:
                  key: otlp-headers
                  name: grafana-secret
            - name: BEYLA_OTEL_METRICS_FEATURES
              value: "network,network_inter_zone"
            - name: BEYLA_PROMETHEUS_PORT
              value: "9090"
            - name: BEYLA_PROMETHEUS_FEATURES
              value: "network,network_inter_zone"
              #value: "application,application_span,application_service_graph,network"
            # - name: BEYLA_PROMETHEUS_FEATURES
            #   value: "application,application_span,application_service_graph,network"
            # - name: BEYLA_PROMETHEUS_PORT
            #   value: "9090"
            - name: BEYLA_PROMETHEUS_TTL
              value: "1m"
            - name: BEYLA_OTEL_METRICS_TTL
              value: "1m"
            - name: OTEL_METRIC_EXPORT_INTERVAL
              value: "10000"
            - name: BEYLA_KUBE_CLUSTER_NAME
              value: "my-local-cluster"
            # - name: BEYLA_KUBE_META_CACHE_ADDRESS
            #   value: "k8s-cache:50055"
            # - name: BEYLA_NETWORK_METRICS
            #   value: "true"
          resources: {}
            
---
kind: Service
apiVersion: v1
metadata:
  name: beyla
spec:
  selector:
    instrumentation: "beyla"
  ports:
    - port: 9090
      protocol: TCP
      targetPort: http
# ---
# kind: Deployment
# apiVersion: apps/v1
# metadata:
#   name: k8s-cache
# spec:
#   selector:
#     matchLabels:
#       instrumentation: k8s-cache
#   template:
#     metadata:
#       labels:
#         instrumentation: k8s-cache
#     spec:

#       serviceAccountName: beyla
#       containers:
#         - name: k8s-cache
#           image: grafana/beyla-k8s-cache:main
#           ports:
#             - containerPort: 50055
#               protocol: TCP
#               name: protobuf
#             - containerPort: 6060
#               protocol: TCP
#               name: profile
#             - containerPort: 9090
#               protocol: TCP
#               name: metrics
#           env:
# #            - name: BEYLA_K8S_CACHE_LOG_LEVEL
# #              value: "debug"
#             - name: BEYLA_K8S_CACHE_PROFILE_PORT
#               value: "6060"
#             - name: BEYLA_K8S_CACHE_INTERNAL_METRICS_PROMETHEUS_PORT
#               value: "9090"
# ---
# kind: Service
# apiVersion: v1
# metadata:
#   name: k8s-cache
# spec:
#   selector:
#     instrumentation: "k8s-cache"
#   ports:
#     - port: 50055
#       protocol: TCP
#       targetPort: protobuf
