apiVersion: v1
kind: Namespace
metadata:
  name: blog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goblog
  namespace: blog
  labels:
    app: goblog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goblog
  template:
    metadata:
      labels:
        app: goblog
    spec:
      containers:
        - name: goblog
          image: mariomac/goblog:dev
          imagePullPolicy: IfNotPresent
          command: [ "/goblog" ]
          env:
            - name: "GOBLOG_CONFIG"
              value: "/sample/config.yml"
          ports:
            - containerPort: 8443
              name: https
---
apiVersion: v1
kind: Service
metadata:
  name: goblog
  namespace: blog
spec:
  selector:
    app: goblog
  ports:
    - port: 8443
      protocol: TCP
      targetPort: https
