version: '3.8'

services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    image: example-frontend
    ports: [ "8080:8080" ]
    environment:
      BACKEND: "http://backend:8080"
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    image: example-backend
    environment:
      WORKERS: 'worker1:5000,worker2:5000,worker3:5000'
  worker1:
    build:
      context: ./worker/
      dockerfile: Dockerfile
    image: example-worker
  worker2:
    build:
      context: ./worker/
      dockerfile: Dockerfile
    image: example-worker
  worker3:
    build:
      context: ./worker/
      dockerfile: Dockerfile
    image: example-worker


  frontend-inst:
    image: mariomac/ebpf-autoinstrument:dev
    pid: "service:frontend"
    privileged: true
    command:
      - /otelauto
      - --config=/configs/cfg.yaml
    volumes:
      - ./configs/:/configs
    env_file:
      - grafana.env
    environment:
      OPEN_PORT: 8080
      OTEL_SERVICE_NAME: frontend
  backend-inst:
    image: mariomac/ebpf-autoinstrument:dev
    pid: "service:backend"
    privileged: true
    command:
      - /otelauto
      - --config=/configs/cfg.yaml
    volumes:
      - ./configs/:/configs
    env_file:
      - grafana.env
    environment:
      OPEN_PORT: 8080
      OTEL_SERVICE_NAME: backend
  worker1-inst:
    image: mariomac/ebpf-autoinstrument:dev
    pid: "service:worker1"
    privileged: true
    env_file:
      - grafana.env
    environment:
      OPEN_PORT: 5000
      OTEL_SERVICE_NAME: worker1
  worker2-inst:
    image: mariomac/ebpf-autoinstrument:dev
    pid: "service:worker2"
    privileged: true
    env_file:
      - grafana.env
    environment:
      OPEN_PORT: 5000
      OTEL_SERVICE_NAME: worker2
  worker3-inst:
    image: mariomac/ebpf-autoinstrument:dev
    pid: "service:worker3"
    privileged: true
    env_file:
      - grafana.env
    environment:
      OPEN_PORT: 5000
      OTEL_SERVICE_NAME: worker3