version: '3.8'

services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    image: example-frontend
    ports: [ "8080:8080" ]
    environment:
      BACKEND: "http://backend:8080"

  frontend-inst:
    image: grafana/beyla:latest
    pid: "service:frontend"
    user: "root"
    cap_add:
      - SYS_ADMIN
      - SYS_RESOURCE
      - SYS_PTRACE
      - BPF
    command:
      - /beyla
      - --config=/configs/cfg.yaml
    volumes:
      - ./configs:/configs
      - ./foo:/sys/fs/bpf
    environment:
      BEYLA_PRINT_TRACES: "true"
      BEYLA_OPEN_PORT: 8080
      BEYLA_BPF_FS_BASE_DIR: "/sys/fs/bpf"



