apiVersion: v1
kind: ServiceAccount
metadata:
  name: obi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: obi
rules:
  - apiGroups: [ "apps" ]
    resources: [ "replicasets" ]
    verbs: [ "list", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "pods", "services", "nodes", "configmaps"]
    verbs: [ "list", "watch", "get" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: obi
subjects:
  - kind: ServiceAccount
    name: obi
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: obi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: obi-config
data:
  obi-config.yml: |
    #    filter:
    #      application:
    #        client:
    #          not_match: 'backend'
    #        server:
    #          not_match: 'backend'
    # trace_printer: text
    # routes:
    #   unmatched: heuristic
    ebpf:
      context_propagation: all
      traffic_control_backend: tcx
      track_request_headers: true
    discovery:
      instrument:
       - k8s_namespace: "*"
      survey:
      - k8s_namespace: "*"
    network:
      enable: true
    attributes:
      kubernetes:
        enable: true
      select:
        "*":
          include: [ "*" ]
          exclude: ["url_path"]
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: obi
spec:
  selector:
    matchLabels:
      instrumentation: obi
  template:
    metadata:
      labels:
        instrumentation: obi
    spec:
      serviceAccountName: obi
      hostPID: true  #important for app instrumentation
      hostNetwork: true #important for network metrics
      volumes:
        - name: obi-config
          configMap:
            name: obi-config
      containers:
        - name: obi
          image: otel/ebpf-instrument:main
          imagePullPolicy: IfNotPresent
          # image: obi:dev
          # imagePullPolicy: Never
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /config
              name: obi-config
          ports:
            - containerPort: 9090
              name: http
            - containerPort: 2345
              name: delve
            - containerPort: 6060
              name: pprof
          env:
            - name: OTEL_EBPF_LOG_LEVEL
              value: "debug"
            - name: OTEL_EBPF_NETWORK_CACHE_MAX_FLOWS
              value: "2"
            - name: OTEL_EBPF_NETWORK_CACHE_ACTIVE_TIMEOUT
              value: "60s"
            - name: OTEL_EBPF_KUBE_CLUSTER_NAME
              value: kind-cluster
            # - name: OTEL_EBPF_LOG_LEVEL
            #   value: "debug"
            # - name: OTEL_EBPF_BPF_DEBUG
            #   value: "true"
#            - name: OTEL_EBPF_PRINT_TRACES
#              value: "true"
            - name: OTEL_EBPF_PROFILE_PORT
              value: "6060"
            - name: OTEL_EBPF_CHANNEL_BUFFER_LEN
              value: "0"
            - name: OTEL_EBPF_CONFIG_PATH
              value: "/config/obi-config.yml"
            - name: OTEL_EBPF_KUBE_METADATA_ENABLE
              value: "true"
            - name: OTEL_EBPF_TRACE_PRINTER
              value: "json"
            # - name: OTEL_EXPORTER_OTLP_ENDPOINT
            #   value: "https://otlp-gateway-prod-eu-west-0.grafana.net/otlp"
            # - name: OTEL_EXPORTER_OTLP_HEADERS
            #   valueFrom:
            #     secretKeyRef:
            #       key: otlp-headers
            #       name: grafana-secret
            - name: OTEL_EBPF_METRICS_FEATURES
              value: "application,application_span,application_service_graph,application_host"
#              value: "application,application_span,application_service_graph,network"
            - name: OTEL_EBPF_PROMETHEUS_PORT
              value: "9090"
            - name: OTEL_EBPF_PROMETHEUS_FEATURES
#              value: "application_service_graph"
              value: "application,application_host"
            - name: OTEL_EBPF_PROMETHEUS_TTL
              value: "1m"
            - name: OTEL_EBPF_METRICS_TTL
              value: "1m"
            - name: OTEL_METRIC_EXPORT_INTERVAL
              value: "10000"
            # - name: OTEL_EBPF_KUBE_META_CACHE_ADDRESS
            #   value: "k8s-cache:50055"
            - name: OTEL_EBPF_INTERNAL_METRICS_EXPORTER
              value: "prometheus"
            - name: OTEL_EBPF_INTERNAL_METRICS_PROMETHEUS_PORT
              value: "9090"
          resources: {}
            
---
kind: Service
apiVersion: v1
metadata:
  name: obi
spec:
  selector:
    instrumentation: "obi"
  ports:
    - name: metrics
      port: 9090
      protocol: TCP
      targetPort: http
    - name: delve
      port: 2345
      protocol: TCP
      targetPort: delve
---
kind: Deployment
apiVersion: apps/v1
metadata:
 name: k8s-cache
spec:
 selector:
   matchLabels:
     instrumentation: k8s-cache
 template:
   metadata:
     labels:
       instrumentation: k8s-cache
   spec:

     serviceAccountName: obi
     containers:
       - name: k8s-cache
         image: mariomac/obi-k8s-cache:dev
         ports:
           - containerPort: 50055
             protocol: TCP
             name: protobuf
           - containerPort: 6060
             protocol: TCP
             name: profile
           - containerPort: 9090
             protocol: TCP
             name: metrics
         env:
#            - name: OTEL_EBPF_K8S_CACHE_LOG_LEVEL
#              value: "debug"
           - name: OTEL_EBPF_K8S_CACHE_PROFILE_PORT
             value: "6060"
           - name: OTEL_EBPF_K8S_CACHE_INTERNAL_METRICS_PROMETHEUS_PORT
             value: "9090"
---
kind: Service
apiVersion: v1
metadata:
 name: k8s-cache
spec:
 selector:
   instrumentation: "k8s-cache"
 ports:
   - port: 50055
     protocol: TCP
     targetPort: protobuf
