apiVersion: v1
kind: ServiceAccount
metadata:
  name: beyla
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: beyla
rules:
  - apiGroups: [ "apps" ]
    resources: [ "replicasets" ]
    verbs: [ "list", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "pods", "services", "nodes" ]
    verbs: [ "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: beyla
subjects:
  - kind: ServiceAccount
    name: beyla
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: beyla
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: beyla-config
data:
  beyla-config.yml: |
    # log_level: debug
    trace_printer: text
    network:
      enable: true
    discovery:
      services:
        - k8s_namespace: demo
    attributes:
      kubernetes:
        enable: true
      select:
        "*":
          include: [ "*" ]
          exclude: [ "url_path" ]
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: beyla
spec:
  selector:
    matchLabels:
      instrumentation: beyla
  template:
    metadata:
      labels:
        instrumentation: beyla
    spec:
      serviceAccountName: beyla
      hostPID: true  #important for app instrumentation
      hostNetwork: true #important for network metrics
      volumes:
        - name: beyla-config
          configMap:
            name: beyla-config
      containers:
        - name: beyla
          image: grafana/beyla-skaffold
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /config
              name: beyla-config
          ports:
            - containerPort: 9090
              name: http
            - containerPort: 6060
              name: pprof
          env:
            - name: BEYLA_PROFILE_PORT
              value: "6060"
            - name: BEYLA_CONFIG_PATH
              value: "/config/beyla-config.yml"
            - name: BEYLA_KUBE_METADATA_ENABLE
              value: "true"
            - name: BEYLA_PROMETHEUS_PORT
              value: "9090"
            - name: BEYLA_LOG_LEVEL
              value: "debug"
            - name: BEYLA_PROMETHEUS_FEATURES
              value: "network"
#            - name: BEYLA_KUBE_CLUSTER_NAME
#              value: "my-local-cluster"
            - name: BEYLA_NETWORK_REVERSE_DNS_TYPE
              value: "ebpf"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "https://otlp-gateway-prod-eu-west-0.grafana.net/otlp"
            - name: OTEL_EXPORTER_OTLP_HEADERS
              valueFrom:
                secretKeyRef:
                  key: otlp-headers
                  name: grafana-secret
            - name: BEYLA_OTEL_METRICS_FEATURES
              value: "network"
#            - name: BEYLA_NETWORK_DEDUPER
#              value: "none"
          resources: {}
---
kind: Service
apiVersion: v1
metadata:
  name: beyla
spec:
  selector:
    instrumentation: "beyla"
  ports:
    - port: 9090
      protocol: TCP
      targetPort: http
      name: http
    - port: 6060
      protocol: TCP
      targetPort: pprof
      name: pprof
